apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-nats-depl
spec:
  selector:
    matchLabels:
      app: iam-nats
  template:
    metadata:
      labels:
        app: iam-nats
    spec:
      containers:
        - name: iam-nats
          image: nats-streaming:0.19.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4222
---
apiVersion: v1
kind: Service
metadata:
  name: iam-nats-srv
spec:
  type: NodePort
  selector:
    app: iam-nats
  ports:
    - port: 4222
      targetPort: 4222
      nodePort: 30202
