apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-redis-depl
spec:
  selector:
    matchLabels:
      app: iam-redis
  template:
    metadata:
      labels:
        app: iam-redis
    spec:
      containers:
        - name: iam-redis
          image: redis:6.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: iam-redis-srv
spec:
  type: NodePort
  selector:
    app: iam-redis
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30201
